default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_exam2_development

test:
  <<: *default
  database: rails_exam2_test

production:
  <<: *default
  database: rails_exam2_production
  username: rails_exam2
  password: <%= ENV['RAILS_EXAM2_DATABASE_PASSWORD'] %>
